// lib/utils/pdf_generator.dart

import 'dart:io';
import 'package:flutter/services.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import '../models/ai_compresive/ai_interpretation_model.dart';

class PdfGenerator {
  /// Generate PDF from AI Interpretation
  static Future<File?> generateInterpretationPDF({
    required AIInterpretationModel interpretation,
    required Map<String, dynamic> chartInfo,
  }) async {
    try {
      final pdf = pw.Document();

      // Add pages
      pdf.addPage(
        pw.MultiPage(
          pageFormat: PdfPageFormat.a4,
          margin: const pw.EdgeInsets.all(40),
          build: (context) => [
            // Title
            pw.Header(
              level: 0,
              child: pw.Text(
                'Astrological Chart Interpretation',
                style: pw.TextStyle(
                  fontSize: 24,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
            ),

            pw.SizedBox(height: 20),

            // Chart Info Section
            pw.Container(
              padding: const pw.EdgeInsets.all(15),
              decoration: pw.BoxDecoration(
                border: pw.Border.all(color: PdfColors.grey400),
                borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
              ),
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text(
                    'Chart Information',
                    style: pw.TextStyle(
                      fontSize: 18,
                      fontWeight: pw.FontWeight.bold,
                    ),
                  ),
                  pw.SizedBox(height: 10),
                  ...chartInfo.entries.map((entry) {
                    return pw.Padding(
                      padding: const pw.EdgeInsets.only(bottom: 5),
                      child: pw.Row(
                        children: [
                          pw.Text(
                            '${entry.key}: ',
                            style: pw.TextStyle(
                              fontWeight: pw.FontWeight.bold,
                            ),
                          ),
                          pw.Text('${entry.value}'),
                        ],
                      ),
                    );
                  }).toList(),
                ],
              ),
            ),

            pw.SizedBox(height: 20),

            // Metadata
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text('System: ${interpretation.system.toUpperCase()}'),
                pw.Text('Word Count: ${interpretation.wordCount}'),
              ],
            ),

            pw.SizedBox(height: 20),

            // Interpretation Content
            pw.Text(
              'Interpretation',
              style: pw.TextStyle(
                fontSize: 18,
                fontWeight: pw.FontWeight.bold,
              ),
            ),

            pw.SizedBox(height: 10),

            // Sections
            ...interpretation.sections.map((section) {
              return pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.SizedBox(height: 15),
                  pw.Text(
                    'Section ${section.number}: ${section.title}',
                    style: pw.TextStyle(
                      fontSize: 16,
                      fontWeight: pw.FontWeight.bold,
                      color: PdfColors.purple700,
                    ),
                  ),
                  pw.SizedBox(height: 8),
                  pw.Text(
                    section.content,
                    textAlign: pw.TextAlign.justify,
                    style: const pw.TextStyle(
                      fontSize: 12,
                      lineSpacing: 1.5,
                    ),
                  ),
                ],
              );
            }).toList(),

            pw.SizedBox(height: 30),

            // Footer
            pw.Divider(),
            pw.SizedBox(height: 10),
            pw.Center(
              child: pw.Text(
                'Generated by Astrology App',
                style: pw.TextStyle(
                  fontSize: 10,
                  color: PdfColors.grey600,
                ),
              ),
            ),
          ],
        ),
      );

      // Save PDF
      final output = await getTemporaryDirectory();
      final timestamp = DateTime.now().millisecondsSinceEpoch;
      final file = File('${output.path}/interpretation_$timestamp.pdf');
      await file.writeAsBytes(await pdf.save());

      print('✅ PDF Generated: ${file.path}');
      return file;
    } catch (e) {
      print('❌ PDF Generation Error: $e');
      return null;
    }
  }

  /// Share PDF
  static Future<void> sharePDF(File pdfFile) async {
    try {
      await Share.shareXFiles(
        [XFile(pdfFile.path)],
        subject: 'Astrological Chart Interpretation',
        text: 'Here is your astrological chart interpretation',
      );
    } catch (e) {
      print('❌ Share Error: $e');
    }
  }

  /// Save PDF to downloads
  static Future<String?> savePDFToDownloads(File pdfFile) async {
    try {
      Directory? downloadsDir;

      if (Platform.isAndroid) {
        downloadsDir = Directory('/storage/emulated/0/Download');
      } else if (Platform.isIOS) {
        downloadsDir = await getApplicationDocumentsDirectory();
      }

      if (downloadsDir != null) {
        final timestamp = DateTime.now().millisecondsSinceEpoch;
        final savedFile = File(
            '${downloadsDir.path}/astro_interpretation_$timestamp.pdf'
        );
        await pdfFile.copy(savedFile.path);

        print('✅ PDF Saved: ${savedFile.path}');
        return savedFile.path;
      }

      return null;
    } catch (e) {
      print('❌ Save Error: $e');
      return null;
    }
  }
}